export interface Review {
    id: number;
    bookId: number;
    name: string;
    description: string;
}

export const mockReviews: Review[] = [
    { id: 1, bookId: 1, name: "Lucía Pérez", description: "Me encantó el desarrollo de personajes. Lo compré y lo terminé en dos días, totalmente recomendable." },
    { id: 2, bookId: 2, name: "Andrés Torres", description: "La edición es excelente y el envío fue rápido. Muy satisfecho con la compra." },
    { id: 3, bookId: 3, name: "Elena Rivas", description: "El libro llegó en buen estado. La historia me atrapó completamente, especialmente los giros del final." },
    { id: 4, bookId: 4, name: "Roberto Díaz", description: "Buena relación calidad-precio. El formato digital es muy cómodo para leer en cualquier parte." },
    { id: 5, bookId: 5, name: "Clara Moreno", description: "Me esperaba algo más de este libro, pero cumple con lo que promete. Entretenido." },
    { id: 6, bookId: 6, name: "Diego Vargas", description: "Ideal para los fans del género. Una experiencia de lectura envolvente. Lo compré por recomendación y valió la pena." },
    { id: 7, bookId: 7, name: "Nuria Castillo", description: "La sinopsis me llamó la atención y el libro no defraudó. Repetiré con este autor." },
    { id: 8, bookId: 8, name: "Jorge Martínez", description: "Lectura obligatoria. El proceso de compra fue sencillo y rápido." },
    { id: 9, bookId: 9, name: "Paula Hernández", description: "Muy buena atención y seguimiento tras la compra. El libro es fantástico." },
    { id: 10, bookId: 10, name: "Héctor Alonso", description: "Lectura ligera y entretenida. Perfecto para leer durante los viajes. Envío puntual." },
    { id: 11, bookId: 11, name: "Isabel Cano", description: "Una obra maestra. Me dejó reflexionando durante días." },
    { id: 12, bookId: 12, name: "Carlos Méndez", description: "Trama envolvente y personajes bien desarrollados. Recomendado." },
    { id: 13, bookId: 13, name: "Ana Beltrán", description: "Un libro que no puedes dejar de leer. Excelente narrativa." },
    { id: 14, bookId: 14, name: "Luis Gutiérrez", description: "Fácil de leer y muy entretenido. Ideal para el fin de semana." },
    { id: 15, bookId: 15, name: "María López", description: "Narración brillante. Me identifiqué mucho con los personajes." },
    { id: 16, bookId: 16, name: "Pedro Ruiz", description: "No es mi estilo habitual, pero me sorprendió gratamente." },
    { id: 17, bookId: 17, name: "Raquel Iglesias", description: "Una historia conmovedora. Muy bien escrita." },
    { id: 18, bookId: 18, name: "Tomás Herrera", description: "Muy recomendable. Buena edición y servicio de entrega." },
    { id: 19, bookId: 19, name: "Lucía Fernández", description: "Te atrapa desde el primer capítulo. Una delicia." },
    { id: 20, bookId: 20, name: "Miguel Ramírez", description: "Lectura obligada para los amantes del género. Excelente." },
    { id: 21, bookId: 21, name: "Alba García", description: "El final fue inesperado y brillante. Una joya." },
    { id: 22, bookId: 22, name: "Sergio Molina", description: "Un viaje emocionante. Totalmente recomendable." },
    { id: 23, bookId: 1, name: "Teresa Ramos", description: "Perfecto para leer con una taza de café. Me encantó." },
    { id: 24, bookId: 2, name: "Iván López", description: "Me pareció lento al inicio, pero mejora mucho luego." },
    { id: 25, bookId: 3, name: "Cristina Morales", description: "Una historia que toca el corazón. Muy emotiva." },
    { id: 26, bookId: 4, name: "Samuel Peña", description: "Cautivador y bien escrito. Me dejó sin palabras." },
    { id: 27, bookId: 5, name: "Beatriz Díaz", description: "Lo devoré en una tarde. Muy recomendable." },
    { id: 28, bookId: 6, name: "Oscar Fernández", description: "Sencillamente genial. Gran calidad literaria." },
    { id: 29, bookId: 7, name: "Lorena Navarro", description: "Un libro que se queda contigo. Lo volvería a leer." },
    { id: 30, bookId: 8, name: "Gabriel Suárez", description: "Maravillosa historia. Gran trabajo del autor." },
    { id: 31, bookId: 9, name: "Carolina Vega", description: "Cada página es un descubrimiento. Excelente." },
    { id: 32, bookId: 10, name: "Rafael Gil", description: "Muy bien escrito. Ritmo perfecto." },
    { id: 33, bookId: 11, name: "Elisa Bravo", description: "Emocionante de principio a fin." },
    { id: 34, bookId: 12, name: "Fernando Ortega", description: "Fácil de leer, difícil de olvidar." },
    { id: 35, bookId: 13, name: "Inés Paredes", description: "Cada capítulo mejor que el anterior. Bravo." },
    { id: 36, bookId: 14, name: "David Cordero", description: "Una joya escondida. Merece más reconocimiento." },
    { id: 37, bookId: 15, name: "Silvia León", description: "Me emocionó mucho. Una historia poderosa." },
    { id: 38, bookId: 16, name: "Martín Aguado", description: "Fascinante y profundo. Excelente autor." },
    { id: 39, bookId: 17, name: "Laura Estevez", description: "Lo disfruté más de lo esperado. Gran recomendación." },
    { id: 40, bookId: 18, name: "Antonio Reyes", description: "Magnífica trama. No decepciona." },
    { id: 41, bookId: 19, name: "Patricia Soto", description: "Me encantó desde la portada hasta el final." },
    { id: 42, bookId: 20, name: "Joaquín Salas", description: "Perfecto equilibrio entre trama y estilo." },
    { id: 43, bookId: 21, name: "Natalia Rojas", description: "Te hace pensar. Muy buena elección." },
    { id: 44, bookId: 22, name: "Eduardo Blanco", description: "Historia envolvente. Repetiré con este autor." },
    { id: 45, bookId: 1, name: "Verónica Torres", description: "Pocas veces un libro me ha conmovido tanto." },
    { id: 46, bookId: 2, name: "Julio Aranda", description: "Muy recomendable. Bien estructurado y claro." },
    { id: 47, bookId: 3, name: "Sandra Valdés", description: "Me atrapó desde el inicio. Genial." },
    { id: 48, bookId: 4, name: "Pablo Marín", description: "Lectura fluida y entretenida." },
    { id: 49, bookId: 5, name: "Alicia Campos", description: "Un final redondo para una gran historia." },
    { id: 50, bookId: 6, name: "Emilio Lara", description: "Gran experiencia de lectura. Lo recomiendo." }
];
